title: Send as POST
description: A share extension for iOS and macOS
url: "https://sendaspost.com"
markdown: kramdown
plugins:
  - jekyll-feed
exclude: ["deploy.sh"]
baseurl: "/"
ios:
  download: "https://itunes.apple.com/us/app/send-as-post/id1321569808?ls=1&mt=8"
  github: "https://github.com/SendAsPost/SendAsPOST"
source: "https://github.com/SendAsPost/sendaspost.com"
