title: Send As POST
description: A share extension for iOS and macOS
url: "https://sendaspost.com"
markdown: kramdown
plugins:
  - jekyll-feed
exclude: ["deploy.sh"]
baseurl: "/"
iosdownload: "https://itunes.apple.com/us/app/send-as-post/id1321569808?ls=1&mt=8"
macosdownload: "https://itunes.apple.com/us/app/send-as-post/id1323106844?ls=1&mt=8"
appsource: "https://github.com/SendAsPost/SendAsPOST"
sitesource: "https://github.com/SendAsPost/sendaspost.com"
